/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionSection: typeof import('./components/OrderForm/AccordionSection.vue')['default']
    BlogSection: typeof import('./components/travellian/BlogSection.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    CartPreviewIcon: typeof import('./components/tools/CartPreviewIcon.vue')['default']
    ChatRoomList: typeof import('./components/chatroom/ChatRoomList.vue')['default']
    CheckoutSteps: typeof import('./components/tools/CheckoutSteps.vue')['default']
    CostSummary: typeof import('./components/OrderForm/CostSummary.vue')['default']
    CustomPhoneCodeSelect: typeof import('./components/OrderForm/CustomPhoneCodeSelect.vue')['default']
    EInvoiceForm: typeof import('./components/OrderForm/EInvoiceForm.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    FloatingChat: typeof import('./components/chatroom/FloatingChat.vue')['default']
    FooterSection: typeof import('./components/travellian/FooterSection.vue')['default']
    GallerySection: typeof import('./components/travellian/GallerySection.vue')['default']
    HeroSection: typeof import('./components/travellian/HeroSection.vue')['default']
    ItemParticipantForm: typeof import('./components/OrderForm/ItemParticipantForm.vue')['default']
    MessageBox: typeof import('./components/chatroom/MessageBox.vue')['default']
    Navbar: typeof import('./components/travellian/Navbar.vue')['default']
    NewsletterSection: typeof import('./components/travellian/NewsletterSection.vue')['default']
    OrderItemsDisplay: typeof import('./components/OrderForm/OrderItemsDisplay.vue')['default']
    ParticipantForm: typeof import('./components/OrderForm/ParticipantForm.vue')['default']
    PaymentOptions: typeof import('./components/OrderForm/PaymentOptions.vue')['default']
    PopularDestinations: typeof import('./components/travellian/PopularDestinations.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingUp: typeof import('./components/singup/SingUp.vue')['default']
    SpecialOffer: typeof import('./components/travellian/SpecialOffer.vue')['default']
    TestimonialSection: typeof import('./components/travellian/TestimonialSection.vue')['default']
    TripPlanners: typeof import('./components/travellian/TripPlanners.vue')['default']
  }
}
